#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os.path

Import('env')

def path4data(fname=""):
  return os.path.join("data", fname)
def path4script(fname=""):
  return os.path.join("scripts", fname)
def path4results(fname=""):
  return os.path.join("results", fname)

versions = env.Command(
  target=path4results("software_versions.tex"),
  source=path4script("software_versions.sh"),
  action="$SOURCE > $TARGET",
)
primers = env.PythonOutput(
  script=env.File(path4script('primers-list.py')),
  target=path4results('primers-list.tex'),
  source=env.File(path4data('primers.json')))

methods = [
  versions,
  primers,
]

Return(['methods'])
